modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JoacoSlime/aestheticweapontrims/issues"
license = "GPLv3"

[[mods]]
modId = "aestheticweapontrims"
version = "${version}"
displayName = "Aesthetic Weapon Trims"
authors = "JoacoSlime & epher"
description = '''
This is a simple mod that adds aesthetical trims for diamond swords.
'''
logoFile = "icon.png"

[[dependencies.aestheticweapontrims]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aestheticweapontrims]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aestheticweapontrims]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "aestheticweapontrims.mixins.json"
